### ISSUE TITLE
Error removing directory

### ISSUE THREAD

**Issue by paloha** [jithu7432/nb-viewer#3]
Hello, thank you for a nice package. I believe you should use `sudo rm -r ./templates` on line 38 of the `install.sh` otherwise you get an error because `./templates` is a directory not a file. Also you could mention that on first use, people need to rigth-click the ipynb file and specify they want to open it with Notebook Viewer by default.

**Comment by jithu7432** [comment]
Hello there, appreciate the love! Please try the latest version.
