### ISSUE TITLE
Missing "build" directory

### ISSUE THREAD

**Issue by raphaeljolivet** [jithu7432/nb-viewer#5]
After cloning the repo and running ./install, I got the following error : 

  Compiling /home/rjolivet/nb-viewer/src/notebook.pyx
  [Errno 2] No such file or directory: '/home/rjolivet/nb-viewer/build/notebook.c'

I add to create the folder `build` myself to make it work.
You should either add "mkdir build" in the install script, or add a dummy file `.keep` in it so that git keeps it.

**Comment by jithu7432** [comment]
Updated the install script [bb105f9a4d75393fbbdc9f2dc59a59b3ca43d8de], marking as closed.
