### ISSUE TITLE
Unable to install on Python-3.8or lower.

### ISSUE THREAD

**Issue by Ravieroy** [jithu7432/nb-viewer#6]
I am on PopOs 20.04 which has Python-3.8.10 but when I try to install using pip it says Python-3.9 or higher is required. I wanted to ask is it really required to have that specific version or higher for it to work? Is it possible to may be somehow install the application in lower versions as well. 

Thank You.

***ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.9; 1.0.1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement nbviewer-gui (from versions: none)
ERROR: No matching distribution found for nbviewer-gui***

**Comment by jithu7432** [comment]
Okay so I did this because I was trying to package this a different way. But for now I don't think that it is necessary.
Edit: I've made the changes, it should work now.

**Comment by Ravieroy** [comment]
Thank you. It works now.
