### ISSUE TITLE
font too small in 4k screen

### ISSUE THREAD

**Issue by victor-moreno** [jithu7432/nb-viewer#8]
Hi,
Thanks for this, it works great.
In a 27" 4k screen the font is very small and it starts maximized. I had to change the code of Class Window  to
```
        self.resize(1600, 2400)
        self.setZoomFactor(2)
#        self.showMaximized()
```
This is in Linux Mint, might be different in other distros.

Perhaps you can add some option to configure the start with arguments for the initial window size, zoom and maximize.

Victor

**Comment by jithu7432** [comment]
Fixed in the new release
